name: Pylint

on:
  push:
    branches:
      - master
      - develop
      - '*'
    # Run only if the commit message contains "run ci"
    if: "contains(github.event.head_commit.message, 'run ci') && (github.ref == 'refs/heads/' + github.event.head_commit.branch)"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
